$schema: https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: os
        properties:
          cache_duration: none
          macos: mac
        template: '{{.Icon}}'
        foreground: '#f8f8f2'
        background: '#6272a4'
        style: diamond
      - type: session
        properties:
          cache_duration: none
        leading_diamond: 
        template: '{{ .UserName }}'
        foreground: '#f8f8f2'
        background: '#6272a4'
        style: diamond
      - type: path
        properties:
          cache_duration: none
          style: mixed
          mixed_threshold: 5
        template: ' {{ .Path }} '
        foreground: '#777268'
        powerline_symbol: 
        background: '#e1fc2f'
        style: powerline
      - type: git
        style: powerline
        powerline_symbol: 
        foreground: '#777268'
        background: '#fec2a4'
        background_templates:
          - '{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}'
          - '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}'
          - '{{ if gt .Ahead 0 }}#B388FF{{ end }}'
          - '{{ if gt .Behind 0 }}#B388FB{{ end }}'
        template: '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus
          }}{{ end }}{{ if .Working.Changed }} 📝 {{ .Working.String }}{{ end }}{{
          if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed
          }} ✅ {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} 💾 {{ .StashCount
          }}{{ end }}'
        properties:
          fetch_status: true
          fetch_upstream_icon: true
          untracked_modes:
            /Users/user/Projects/oh-my-posh/: 'no'
          source: cli
          mapped_branches:
            feature/*: '🚀 '
            release/*: '🎁 '
            topic/*: '👕 '
            bug/*: '🐛 '
      - type: node
        properties:
          cache_duration: none
        template: '  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end
          }}{{ .Full }} '
        foreground: '#f8f8f2'
        powerline_symbol: 
        background: '#8be9fd'
        style: powerline
      - type: go
        properties:
          cache_duration: none
        template: ' {{ .Full }} '
        foreground: '#ffffff'
        powerline_symbol: 
        background: '#7FD5EA'
        style: powerline
      - type: java
        properties:
          cache_duration: none
        template: '  {{ .Full }}'
        foreground: '#777268'
        powerline_symbol: 
        background: '#fcabc3'
        style: powerline
      - type: python
        properties:
          cache_duration: none
        template: ' 🐍 {{ .Full }} '
        foreground: '#100e23'
        powerline_symbol: 
        background: '#906cff'
        style: powerline
      - type: rust
        properties:
          cache_duration: none
        template: '  {{ .Full }} '
        foreground: '#193549'
        powerline_symbol: 
        background: '#99908a'
        style: powerline
      - type: docker
        properties:
          cache_duration: none
        template: ' 🐳 {{ .Context }} '
        foreground: '#000000'
        powerline_symbol: 
        background: '#0B59E7'
        style: powerline
      - type: kubectl
        style: powerline
        powerline_symbol: 
        foreground: '#777268'
        background: '#abddfc'
        template: '☸ {{if .Namespace}}{{.Namespace}}{{end}} '
        properties:
          context_aliases:
            arn:aws:eks:eu-west-1:1234567890:cluster/posh: posh
  - type: prompt
    alignment: left
    segments:
      - properties:
          always_enabled: true
          cache_duration: none
        template: '>>'
        foreground: '#22f8ff'
        type: status
        style: plain
        foreground_templates:
          - '{{ if gt .Code 0 }}#ef5350{{ end }}'
    newline: true
  - type: rprompt
    alignment: left
    segments:
      - properties:
          cache_duration: none
        leading_diamond: 
        trailing_diamond: 
        template: ' ☁ {{.Profile}}{{if .Region}}@{{.Region}}{{end}}'
        foreground: '#282a36'
        background: '#f1fa8c'
        type: aws
        style: diamond
        invert_powerline: true
      - properties:
          cache_duration: none
          time_format: '15:04'
        trailing_diamond: 
        template: ' ♥️ {{ .CurrentDate | date .Format }} '
        foreground: '#f8f8f2'
        background: '#ff79c6'
        type: time
        style: diamond
version: 3
final_space: true
